server:
  port: 7081

spring:
  application:
    name: "StaffManagerSystem"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/staffmanager?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: net.tdiant.hnist.homework.staffmanagersystem
  configuration:
    map-underscore-to-camel-case: true
